### ISSUE TITLE
Removing system files

### ISSUE THREAD

**Issue by willzeng** [dsfranca/KnowYourLimit#4]
It looks like there are some system files sticking around in the repo that could be removed:
`.vscode` is ignored in the https://github.com/dsfranca/KnowYourLimit/blob/main/.gitignore
`.ipynb_checkpoints` and `__pycache__` can also likely be git removed.

Any reason to keep them around? @dsfranca

**Comment by mstechly** [comment]
You could use a default `.gitignore` file like the one here: https://github.com/github/gitignore/blob/main/Python.gitignore

**Comment by dsfranca** [comment]
Thanks! I will follow the solution suggested by @mstechly!

**Comment by dsfranca** [comment]
Done!
