### ISSUE TITLE
Module structure for https://github.com/dsfranca/KnowYourLimit/blob/main/cirq_circuits.py

### ISSUE THREAD

**Issue by willzeng** [dsfranca/KnowYourLimit#9]
This module has some modular functions, but there's also:
-  e.g. [blocks of comments](https://github.com/dsfranca/KnowYourLimit/blob/main/cirq_circuits.py#L43-L96)
- module level code: https://github.com/dsfranca/KnowYourLimit/blob/main/cirq_circuits.py#L43-L96

It wasn't clear to me that any of the examples use the module level code. Can this just be removed?

**Comment by dsfranca** [comment]
Nice catch! That file (and SDP.py) should actually have been deleted a long time ago... I deleted them them now!
